# Generated by Django 2.2.5 on 2020-02-22 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_System', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal', to='CRUD_System.School'),
        ),
    ]
